name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

     

      - name: Upload MochaAwesome HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: MochaAwesome HTML Report
          path: cypress/reports

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff0000'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: Test Automation Report <https://github.com/Muhammad786Aqib/Cypress-E2E/actions/runs/${{github.run_id}}
          SLACK_TITLE: Cypress Web Test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


